
class Emoji:
    CHECK_MARK = '\N{HEAVY CHECK MARK}'
    CROSS_MARK = '\N{HEAVY MULTIPLICATION X}'
    THUMBS_UP = '\N{THUMBS UP SIGN}'
    THUMBS_DOWN = '\N{THUMBS DOWN SIGN}'
    BALLOT_BOX = '\N{BALLOT BOX WITH BALLOT}'
